CREATE TABLE IF NOT EXISTS NOBEL_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT 
);
INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
  (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
  (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
  (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
  (1971, 'CHEMISTRY', 'HANNES', 'SWEDEN', 'LINGUIST'),
  (1972, 'LITERATURE', 'HANN', 'GERMANY', 'ECONOMIST'),
  (1972, 'ECONOMICS', 'ALFVEN', 'RUSSIA', 'ECONOMIST'),
  (1973, 'BIOLOGY', 'HALFVEN', 'USA', 'PRIME MINISTER'),
  (1980, 'BIOLOGY', 'HANALFVEN', 'USA', 'PRESIDENT'),
  (1981, 'PHYSIOLOGY', 'HAALFVEN', 'HUNGARY', 'SCIENTIST'),
  (1975, 'PHYSICS', 'HANNESN', 'CHILE', 'SCIENTIST');

SELECT *
FORM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';